### ISSUE TITLE
How to process VTAB dataset?

### ISSUE THREAD

**Issue by kai-wen-yang** [dongzelian/SSF#1]
I have followed the vpt repo to process VTAB dataset, but I only get some tfrecord files.
How to further process them?

**Comment by dongzelian** [comment]
@kai-wen-yang The processing of the VTAB dataset is tricky. I have uploaded our extracted vtab-1k dataset (images and txt). See https://github.com/dongzelian/SSF/blob/main/README.md.

**Comment by kai-wen-yang** [comment]
Thank you much. It really helps me a lot!

**Comment by dongzelian** [comment]
@kai-wen-yang Welcome
