### ISSUE TITLE
About the train and test data in VTAB.

### ISSUE THREAD

**Issue by Tommy-yours** [dongzelian/SSF#10]
Hi, I have a question about the train and test data in VTAB. In the paper VPT, I note that they use the train800.txt to train the model to find the best model on val200.txt, and then they use train800val200.txt to run three rounds to report the average accuracy on the test data. In your released code, I want to know how you deal with the train, val, and test data? It seems that you train the model on train800val200.txt and then report the test accuracy based on the last trained model? Looking forward to your reply.
code:
train_list_path = os.path.join(self.dataset_root, 'train800val200.txt')
test_list_path = os.path.join(self.dataset_root, 'test.txt')
# train_list_path = os.path.join(self.dataset_root, 'train800.txt')
# test_list_path = os.path.join(self.dataset_root, 'val200.txt')

**Comment by dongzelian** [comment]
@Tommy-yours Thanks. We use val200.txt to choose the best model.

**Comment by Tommy-yours** [comment]
Thank you for your reply.
