### ISSUE TITLE
Performance on stanford_dogs.

### ISSUE THREAD

**Issue by Yewen1486** [dongzelian/SSF#12]
Hi dongze,

Scripts on CUB works well. After running the script for stanfordcars dataset, I only got 88.82 top1 acc(different from the reported 89.6). Is there anything wrong with the released training scripts on stanfordcars dataset? Or did I made any mistake for running the script? 

Thanks for your help!

Best.

**Comment by dongzelian** [comment]
@Yewen1486 Do you mean stanford_cars or stanford_dogs? You can check the train/val/test split.

**Comment by Yewen1486** [comment]
Oh, indeed it should be stanford_dogs. I'm using train(12000 images)/test(8580 images) splits(http://vision.stanford.edu/aditya86/ImageNetDogs/main.html) without val set. Should I follow the train(10800)/val(1200)/test (8580)split in VPT exactly? Thanks.

**Comment by dongzelian** [comment]
@Yewen1486 I have updated a new training script for stanford_dogs. You can get a slightly better result.

**Comment by Yewen1486** [comment]
Thanks a lot, it works.
