### ISSUE TITLE
Training script for baselines

### ISSUE THREAD

**Issue by yaohuicai** [dongzelian/SSF#2]
This is a wonderful paper! And also thank you for your neat codebase.

I am wondering if you can provide code for reproducing full-finetuning and linear-probing baselines in the paper. That would be very helpful.

**Comment by dongzelian** [comment]
@yaohuicai Thanks for your interest. I just finished the scripts for full fine-tuning and linear probing due to the recent CVPR deadline. Now I have uploaded them. Hope it will be useful for you.

**Comment by dongzelian** [comment]
@yaohuicai Thanks for your interest. Sorry for the delay of a few days due to the recent CVPR deadline. Now I have uploaded the scripts for full fine-tuning and linear probing. Hope it will be useful for you.
