### ISSUE TITLE
About the performance.

### ISSUE THREAD

**Issue by weeknan** [dongzelian/SSF#5]
In the paper, Table 1 shows SSF gets 93.99% top-1 Acc using ViT-B/16 on CIFAR100. However, in Table 4, SSF gets 69.0% top-1 Acc using ViT-B/16 on CIFAR100. Are there any different settings between these two results?  It seems like using the same model.

**Comment by JieShibo** [comment]
Hi. The cifar100 dataset in vtab1k benchmark only uses 1000 training samples, while Table 1 shows results on full cifar100 dataset with 50000 training images.
Details in Table 8.

**Comment by weeknan** [comment]
i see, thank you!
