### ISSUE TITLE
Preprosessed vtab-1k zip file is broken

### ISSUE THREAD

**Issue by yushuinanrong** [dongzelian/SSF#7]
Hi authors,

Thank you for sharing the source code for you inspirational work! I wanted to mention to you that the vtab-1k dataset you shared on onedrive seems broken. The error message I got when I tried to unzip the file is "Error 79 - Inappropriate file type or format". Could you kindly help to look into the issue?

Update:
I figured out the correct way to unzip the five split .tar.gz files. The following command works for me 
```
cat filename.tar.gz.* | tar -zxv
```

**Comment by xuweigogogo** [comment]
> Hi authors,
> 
> Thank you for sharing the source code for you inspirational work! I wanted to mention to you that the vtab-1k dataset you shared on onedrive seems broken. The error message I got when I tried to unzip the file is "Error 79 - Inappropriate file type or format". Could you kindly help to look into the issue?
> 
> Update: I figured out the correct way to unzip the five split .tar.gz files. The following command works for me
> 
> ```
> cat filename.tar.gz.* | tar -zxv
> ```

have you deal with this problem @yushuinanrong
